{{- if eq .Values.mqtt.protocol "ssl" }}
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ include "mqtt-influxdb-sinker.fullname" . }}-root-cert
spec:
  backendType: secretsManager
  data:
    - key: {{ .Values.externalSecretRootCert }}
      name: root.ca
{{- end }}
