spec:
  project: proj-topic-thunder
  destination:
    server: https://kubernetes.default.svc
    namePrefix: ""
  source:
    repoURL: https://github.com/rcompos/topic-thunder
    targetRevision: main

# Values file used by downstream apps
valueFiles:
  - values-lucky.yaml

# Application Definitions
#
# apps: 
#   appNickname:                      # Go conforming name (camelCase)
#     name: name-of-app               # Canonical app name (required)
#     values: values-my-env.yaml      # Values file (optional)
#     namespace: custom-namespace     # Namespace (optional)
#     repo: https://gitlab.corp.atieva.com/data/my-repo.git   # Git chart repo (optional)
#     path: path/to/my-chart          # Path under chart repo (optional)
#     targetRev: my/branch            # Git branch (optional)
#     ignoreDiffs: true               # Ignore CRD diffs

apps:
  metalLB:
    name: metallb
    values: ""
    namespace: ""
    repo: ""
    path: ""
    targetRev: ""
    ignoreDiffs: true
  openebs:
    name: openebs
    values: ""
    namespace: ""
    repo: ""
    path: ""
    targetRev: ""
    ignoreDiffs: true
  ingressNginx:
    name: ingress-nginx
    values: ""
    namespace: ""
    repo: ""
    path: ""
    targetRev: ""
    ignoreDiffs: true
  metricsServer:
    name: metrics-server
    values: ""
    namespace: ""
    repo: ""
    path: ""
    targetRev: ""
    ignoreDiffs: true
  kubePrometheusStack:
    name: kube-prometheus-stack
    values: ""
    namespace: "monitoring"
    repo: ""
    path: ""
    targetRev: ""
    ignoreDiffs: true
  grafana:
    name: grafana
    values: ""
    namespace: "monitoring"
    repo: ""
    path: ""
    targetRev: ""
    ignoreDiffs: true
  emqxEE:
    name: emqx-ee
    values: ""
    namespace: ""
    repo: ""
    path: ""
    targetRev: ""
    ignoreDiffs: true
  strimziKafkaOperator:
    name: strimzi-kafka-operator
    values: ""
    namespace: ""
    repo: ""
    path: ""
    targetRev: ""
    ignoreDiffs: true
  kafka:
    name: kafka
    values: ""
    namespace: ""
    repo: ""
    path: ""
    targetRev: ""
    ignoreDiffs: true
  kafkaUI:
    name: kafka-ui
    values: ""
    namespace: ""
    repo: ""
    path: ""
    targetRev: ""
    ignoreDiffs: true
  spark:
    name: spark
    values: ""
    namespace: ""
    repo: ""
    path: ""
    targetRev: ""
    ignoreDiffs: true
