# Default values for mqtt-influxdb-sinker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 752838837007.dkr.ecr.us-west-2.amazonaws.com/mqtt-influxdb-sinker
  imagePullPolicy: IfNotPresent

mqtt:
  #server: emqx.default.svc.cluster.local
  #server: emqx-prod-emqx-ee-headless.emqx-prod.svc
  server: emqx-beta-emqx-ee-headless.emqx-beta.svc
  port: 1883
  topic: "car/beta/+/+"
  client:
    id: "mqtt-influxdb-scala"
  qos: 1

influxdb:
  server: "influxdb-data.influxdb"
  port: 8086
  db: "mqtt_messages"
  retention: mqtt

resources:
  requests:
    cpu: 1000m
    memory: 1024Mi
  limits:
    cpu: 2000m
    memory: 2048Mi

nodeSelector:
  nodeType: cpuOptimized

tolerations:
- key: nodeType
  value: cpuOptimized
  operator: Equal
  effect: NoSchedule
