# Default values for mqtt-influxdb-sinker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 752838837007.dkr.ecr.us-west-2.amazonaws.com/mqtt-influxdb-sinker
  imagePullPolicy: IfNotPresent

mqtt:
  protocol: ssl
  server: emqx-prod.sol.prod.dataeng.pdx.atieva.com
  port: 8883
  topic: "car/beta/+/+"
  cluster:
    id: "sol"
  client:
    id: "mqtt-influxdb-scala"
  qos: 1

influxdb:
  server: "influxdb-data.influxdb"
  port: 8086
  db: "mqtt_messages"
  retention: mqtt

externalSecretRootCert: sol-emqx-client-rsa-ca
externalSecretKeyFile: sol-emqx-client-mqtt-rsa-key
externalSecretCertFile: sol-emqx-client-rsa-cert

resources:
  requests:
    cpu: 1000m
    memory: 1024Mi
  limits:
    cpu: 2000m
    memory: 2048Mi

nodeSelector:
  nodeType: cpuOptimized

tolerations:
- key: nodeType
  value: cpuOptimized
  operator: Equal
  effect: NoSchedule

encrypt:
    hash: 
        enable: "false"
    secret:
        name: "data-production-sol-lucid-key-master"
    aws:
        region: us-west-2 
